version: "3.2"

services:
  patches-and-areas-api:
    image: patches-and-areas-api
    build:
      context: .
      dockerfile: PatchesAndAreasApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - Localstack_SnsServiceUrl=http://localstack:4566
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - ASSET_ADMIN_GROUPS=mmh-project-team
    links:
      - dynamodb-database
      - localstack

  patches-and-areas-api-test:
    image: patches-and-areas-api-test
    build:
      context: .
      dockerfile: PatchesAndAreasApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - Localstack_SnsServiceUrl=http://localstack:4566
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - ASSET_ADMIN_GROUPS=e2e-testing
    links:
      - dynamodb-database
      - localstack

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
      
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.14.1
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
