// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructQuery(System.Guid)~PatchesApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Controllers.PatchesApiControllerTests.ConstructQuery~PatchesApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.UseCase.GetByIdUseCaseTests.ConstructQuery~PatchesApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Fixtures.PatchesFixtures._dbContext")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.E2ETests.Fixtures.PatchesFixtures.GivenAPersonDoesNotExist")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps._httpClient")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps._lastResponse")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps._jsonOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps.CreateJsonOptions~System.Text.Json.JsonSerializerOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Controllers.PatchesApiControllerTests.ConstructUpdateQuery~PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.UseCase.UpdatePatchResponsibilitiesUseCaseTests.ConstructQuery(System.Nullable{System.Guid},System.Nullable{System.Guid})~PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructUpdateNameRequest~PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructUpdateQuery(System.Guid,System.Guid)~PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps._disposed")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Steps.BaseSteps._cleanup")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.E2ETests.Steps.UpdatePatchResponsibilityStep.CallAPI(System.Guid,System.Guid,PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject,System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Stories.GetPatchByIdTests._steps")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.E2ETests.Steps.UpdatePatchResponsibilityStep.WhenPatchDetailsAreRequested(System.Guid,System.Guid,PatchesApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject,System.Nullable{System.Int32})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.Controllers.PatchesApiControllerTests.ConstructQueryParameter~PatchesApi.V1.Boundary.Request.GetPatchByParentIdQuery")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesApi.Tests.V1.UseCase.GetPatchByParentIdUseCaseTests.ConstructQueryParameter~PatchesApi.V1.Boundary.Request.GetPatchByParentIdQuery")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:PatchesApi.Tests.DynamoDbIntegrationTests`1.PatchByParentId")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:PatchesApi.Tests.DynamoDbIntegrationTests`1.PatchByParentId")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesApi.Tests.V1.E2ETests.Stories.GetPatchByParentIdTests._steps")]
