// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructQuery(System.Guid)~PatchesAndAreasApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Controllers.PatchesAndAreasApiControllerTests.ConstructQuery~PatchesAndAreasApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.UseCase.GetByIdUseCaseTests.ConstructQuery~PatchesAndAreasApi.V1.Boundary.Request.PatchesQueryObject")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Fixtures.PatchesFixtures._dbContext")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Fixtures.PatchesFixtures.GivenAPersonDoesNotExist")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._httpClient")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._lastResponse")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._jsonOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps.CreateJsonOptions~System.Text.Json.JsonSerializerOptions")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.DeleteResponsibilityFromPatchStep.WhenDeleteResponsibilityFromPatchApiIsCalledAsync(PatchesAndAreasApi.V1.Boundary.Request.DeleteResponsibilityFromPatchRequest)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.DeleteResponsibilityFromPatchStep.ResponsibilityRemovedFromPatch(System.Guid,System.Guid,PatchesAndAreasApi.Tests.V1.E2ETests.Fixtures.PatchesFixtures)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps.Dispose")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._disposed")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._cleanup")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Controllers.PatchesAndAreasApiControllerTests.ConstructUpdateQuery~PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.UseCase.UpdatePatchResponsibilitiesUseCaseTests.ConstructQuery(System.Nullable{System.Guid},System.Nullable{System.Guid})~PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructUpdateNameRequest~PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructUpdateQuery(System.Guid,System.Guid)~PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilityRequest")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._disposed")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.BaseSteps._cleanup")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.UpdatePatchResponsibilityStep.CallAPI(System.Guid,System.Guid,PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject,System.Nullable{System.Int32})~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Stories.GetPatchByIdTests._steps")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.E2ETests.Steps.UpdatePatchResponsibilityStep.WhenPatchDetailsAreRequested(System.Guid,System.Guid,PatchesAndAreasApi.V1.Boundary.Request.UpdatePatchesResponsibilitiesRequestObject,System.Nullable{System.Int32})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.Controllers.PatchesAndAreasApiControllerTests.ConstructQueryParameter~PatchesAndAreasApi.V1.Boundary.Request.GetPatchByParentIdQuery")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:PatchesAndAreasApi.Tests.V1.UseCase.GetPatchByParentIdUseCaseTests.ConstructQueryParameter~PatchesAndAreasApi.V1.Boundary.Request.GetPatchByParentIdQuery")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:PatchesAndAreasApi.Tests.DynamoDbIntegrationTests`1.PatchByParentId")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:PatchesAndAreasApi.Tests.DynamoDbIntegrationTests`1.PatchByParentId")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:PatchesAndAreasApi.Tests.V1.E2ETests.Stories.GetPatchByParentIdTests._steps")]
